//! ════════════════════════════════════════════════════════════════
//! ENGINE 281: CODEGEN — Self Recursive Code Generator
//! ════════════════════════════════════════════════════════════════
//!
//! Generates random valid .glx programs, assembles them to .gbin,
//! and drops them into the Will inbox for directed evolution.
//!
//! This is the "mouth" of the autonomous loop:
//!   codegen → assembler → will → archive → SKVA → codegen
//!
//! Programs are generated from a grammar of valid opcode sequences
//! with resonance-weighted randomization.

use std::path::Path;
use genlex_types::SOVEREIGN_ANCHOR;
use dialect_genlex::assembler;

/// Program generation strategy
#[derive(Debug, Clone, Copy)]
pub enum Strategy {
    /// Random arithmetic chains
    Arithmetic,
    /// Resonance-heavy (PULSE/RESONATE/EMBED)
    Resonance,
    /// Loop-based iterative programs
    Iterative,
    /// Mixed strategy (weighted random)
    Mixed,
}

/// A generated program
#[derive(Debug)]
pub struct GeneratedProgram {
    pub source: String,
    pub binary: Vec<u8>,
    pub strategy: Strategy,
    pub instruction_count: usize,
}

/// Simple deterministic RNG (xorshift64) — no external deps
struct Rng {
    state: u64,
}

impl Rng {
    fn new(seed: u64) -> Self {
        Rng { state: seed.max(1) }
    }

    fn next(&mut self) -> u64 {
        self.state ^= self.state << 13;
        self.state ^= self.state >> 7;
        self.state ^= self.state << 17;
        self.state
    }

    fn range(&mut self, low: u64, high: u64) -> u64 {
        if high <= low { return low; }
        low + (self.next() % (high - low))
    }

    fn pick<'a, T>(&mut self, items: &'a [T]) -> &'a T {
        let idx = self.range(0, items.len() as u64) as usize;
        &items[idx]
    }

    fn float(&mut self) -> f32 {
        (self.next() % 10000) as f32 / 10000.0
    }
}

/// Core arithmetic opcodes (safe, always valid)
const ARITH_OPS: &[&str] = &["ADD", "SUB", "MUL", "DIV", "SQRT", "SIN"];

/// Resonance opcodes
const RESONANCE_OPS: &[&str] = &["PULSE", "RESONATE", "EMBED", "DENSITY"];

/// All registers
const REGS: &[&str] = &["r0", "r1", "r2", "r3", "r4", "r5", "r6", "r7"];

/// Generate a random valid .glx program
pub fn generate(strategy: Strategy, seed: u64, min_ops: usize, max_ops: usize) -> GeneratedProgram {
    let mut rng = Rng::new(seed);
    let mut lines: Vec<String> = Vec::new();

    // Header comment
    lines.push(format!("; Generated by Engine 281 (seed={})", seed));
    lines.push(format!("; Strategy: {:?}", strategy));

    // Always load ANCHOR into r7 (reserved for resonance)
    lines.push(format!("LOAD_IMM r7 #ANCHOR       ; sovereign constant"));

    // Load initial values into registers
    let num_loads = rng.range(2, 5) as usize;
    for i in 0..num_loads {
        let val = match strategy {
            Strategy::Resonance => {
                // Values near ANCHOR harmonics
                let harmonic = rng.range(1, 8) as f32;
                SOVEREIGN_ANCHOR * harmonic
            }
            _ => {
                // Random floats
                rng.float() * 100.0
            }
        };
        lines.push(format!("LOAD_IMM r{} #{:.4}        ; init", i, val));
    }

    // Generate body
    let body_len = rng.range(min_ops as u64, max_ops as u64) as usize;

    match strategy {
        Strategy::Arithmetic => {
            for _ in 0..body_len {
                let op = rng.pick(ARITH_OPS);
                let ra = rng.pick(REGS);
                let rb = rng.pick(REGS);
                if *op == "SQRT" || *op == "SIN" {
                    lines.push(format!("{} {} 0 0", op, ra));
                } else {
                    lines.push(format!("{} {} {} 0", op, ra, rb));
                }
            }
        }
        Strategy::Resonance => {
            for _ in 0..body_len {
                let op = if rng.float() < 0.6 {
                    rng.pick(RESONANCE_OPS)
                } else {
                    rng.pick(ARITH_OPS)
                };
                let ra = rng.pick(REGS);
                if *op == "SQRT" || *op == "SIN" || *op == "PULSE" || *op == "DENSITY" {
                    lines.push(format!("{} {} 0 0", op, ra));
                } else if *op == "RESONATE" || *op == "EMBED" {
                    lines.push(format!("{} {} r7 0", op, ra));
                } else {
                    let rb = rng.pick(REGS);
                    lines.push(format!("{} {} {} 0", op, ra, rb));
                }
            }
        }
        Strategy::Iterative => {
            // Generate a loop
            lines.push(format!("LOAD_IMM r5 #{}.0        ; loop counter",
                rng.range(3, 12)));
            lines.push(":loop".to_string());

            for _ in 0..(body_len / 2).max(2) {
                let op = rng.pick(ARITH_OPS);
                let ra = rng.pick(&REGS[..4]); // use r0-r3 for data
                let rb = rng.pick(&REGS[..4]);
                if *op == "SQRT" || *op == "SIN" {
                    lines.push(format!("{} {} 0 0", op, ra));
                } else {
                    lines.push(format!("{} {} {} 0", op, ra, rb));
                }
            }

            // Pulse for resonance
            lines.push("PULSE r0 0 0".to_string());

            // Decrement and loop
            lines.push("LOAD_IMM r6 #1.0        ; decrement".to_string());
            lines.push("SUB r5 r6 0".to_string());
            lines.push("CMP_GT r5 r6 0".to_string());
            lines.push("JUMP_IF :loop 0 0".to_string());
        }
        Strategy::Mixed => {
            // Alternate strategies
            for i in 0..body_len {
                let sub = match i % 3 {
                    0 => Strategy::Arithmetic,
                    1 => Strategy::Resonance,
                    _ => Strategy::Arithmetic,
                };
                let op = match sub {
                    Strategy::Resonance => {
                        if rng.float() < 0.5 { rng.pick(RESONANCE_OPS) }
                        else { rng.pick(ARITH_OPS) }
                    }
                    _ => rng.pick(ARITH_OPS),
                };
                let ra = rng.pick(REGS);
                if *op == "SQRT" || *op == "SIN" || *op == "PULSE" || *op == "DENSITY" {
                    lines.push(format!("{} {} 0 0", op, ra));
                } else {
                    let rb = rng.pick(REGS);
                    lines.push(format!("{} {} {} 0", op, ra, rb));
                }
            }
        }
    }

    // Store result and halt
    lines.push("STORE_OUT r0 0 0          ; emit result".to_string());
    lines.push("HALT".to_string());

    let source = lines.join("\n");

    // Assemble to binary
    let result = assembler::assemble(&source).unwrap_or_else(|e| {
        panic!("[CODEGEN] Assembly failed for seed {}: {}", seed, e);
    });

    GeneratedProgram {
        instruction_count: result.instructions,
        binary: result.binary,
        strategy,
        source,
    }
}

/// Generate a batch of programs and write them to the Will inbox
pub fn seed_inbox(inbox_path: &Path, count: usize, base_seed: u64) -> Vec<String> {
    let strategies = [
        Strategy::Arithmetic,
        Strategy::Resonance,
        Strategy::Iterative,
        Strategy::Mixed,
    ];

    std::fs::create_dir_all(inbox_path).ok();

    let mut paths = Vec::new();

    for i in 0..count {
        let strategy = strategies[i % strategies.len()];
        let seed = base_seed + i as u64;
        let program = generate(strategy, seed, 4, 12);

        let filename = format!("gen_{:04}_{:?}.gbin", i, strategy);
        let path = inbox_path.join(&filename);

        std::fs::write(&path, &program.binary).unwrap();
        println!("[CODEGEN] {} | {:?} | {} inst | {} bytes",
            filename, program.strategy,
            program.instruction_count, program.binary.len());

        paths.push(path.to_string_lossy().to_string());
    }

    println!("[CODEGEN] Seeded {} programs into {:?}", count, inbox_path);
    paths
}
